### ISSUE TITLE
Last zone and associated sensors not set

### ISSUE THREAD

**Issue by ptaylor74** [gcobb321/icloud3#93] opened 2020-11-06 00:43 UTC
Hi Gary

As of 2.2.1 (including 2.2.1a) I note the last_zone attribute within the device_tracker and the associated sensors are not being set irrespective of zone transitions.  The follow example is the end result of my wife being at home, departing, passing through at least one other zone before arriving at her destination.  
![device_tracker](https://user-images.githubusercontent.com/49575302/98311950-c02cb900-2024-11eb-99d5-36b7de188409.png)
![current_zone_sensors](https://user-images.githubusercontent.com/49575302/98311958-c58a0380-2024-11eb-8a6c-3e628a144a28.png)
![last_zone_sensors](https://user-images.githubusercontent.com/49575302/98311969-cfac0200-2024-11eb-87da-166a3be778c3.png)

**Comment by gcobb321** [comment] 2020-11-08 16:45
I may have found the bug and am working on an update.

**Comment by ptaylor74** [comment] 2020-11-09 02:32
Thanks Gary.  Much appreciated.  I should have added to the original ticket that the issue is universal for me across all 3 iOS trackers that I use.

Thanks again.

**Comment by gcobb321** [comment] 2020-11-09 20:38
iCloud3 v2.2.2d has been uploaded to the development-v2.2.2 directory [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.2.2)
____________________________________________________________
iCloud3 now works with Real 2fa Support
------------------
This is significant update to iCloud3. It supports true 2fa verification using the 6-digit Apple ID Verification Code sent from Apple when you log into iCloud.

Download the zip file from the development-v2.2.2 directory [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.2.2), unzip it into the icloud3 directory and restart HA.

When iCloud3 starts, you will get the standard Apple Login warning and the 6-digit Apple ID Verification Code notification. YOU WILL USE THAT 6-DIGIT CODE IN THE ID ENTRY SCREEN ON THE HA NOTIFICATIONS AREA. Select the Verification Code entry window like you always have from the HA Notifications area and enter the 6-digit code. This will create the Trusted Device token like other apps and browsers. iCloud3 will then continue starting as it usually does.

Other changes:
---------------------
Deleted parameter
*display_zone_fname: True/False* has been eliminated.

New Parameter:
*display_zone_format: name/title/fname/zone,  Default: name*

This parameter indicates how the zone should be displayed in the device_tracker.[DEVICENAME] states field and on the Event Log. The zone is formatted as follows:
- name - A reformatted zone name. Examples: 'the_shores' is displayed as 'TheShores' 
- title - A reformatted zone name. Example: 'the_shores' is displayed as 'The Shores'
- fname - The zones Friendly Name. Example: 'The Shores Development'
- zone - The actual zone name is displayed. Example: 'the_shores' is displayed as 'the_shores'

Bug Fix (I think)
-----------------
The *sensor.[DEVICENAME_last_zone* values should be correct.

**Comment by gcobb321** [comment] 2020-11-09 20:55
I haven't announced this yet on the v2.2 Forum yet. I thought I'd release it to you first. Let me know if everything works OK or doesn't work. Also, look at the last_zone values and  let me know if they are correct.

**Comment by ptaylor74** [comment] 2020-11-10 08:52
Thanks Gary.  Sorry, just getting to this now.  I'll update and test this evening.  Cheers!

**Comment by ptaylor74** [comment] 2020-11-10 11:49
Not what I would call extensive testing on my side but I have progression tested:
1) 2fa - Working beautifully.  Thank you for that;  I have been using a second "friend" account to avoid that to date.
2) last_zone issue.   Everything seems to be working perfectly so far.   
3) display_zone_format.  This appears to be an issue.  I have updated ic3 with 'display_zone_format: fname' but I am not having any luck.  The device_tracker state still appears to present as the zone name.  I'll need to test further as I haven't had a chance to try the other options.

Thanks again Gary.  Greatly appreciated.

**Comment by gcobb321** [comment] 2020-11-10 20:16
3. *display_name_format: fname* -- I'm not seeing any problems here.
On my system:
From Development > States:  zone.ind_river_shores, friendly_name: Indian River Shores
From Development > States:  device_tracker.gary_iphone, state: Indian River Shores

name displayes 'IndRiverShores'
title displayes 'Ind River Shores'

**Comment by gcobb321** [comment] 2020-12-13 20:57
This should be fixed now. Reopen the issue is you find a problem. Release Candidate 7 was just uploaded.

**Closed as completed by gcobb321** 2020-12-13 20:57 UTC
