### ISSUE TITLE
In 2.2.0 RC8 version, the location is still not updated

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#50] opened 2020-07-01 03:45 UTC
When the location was not updated, I checked the log without any error. Then I tried to call icloud3_UPDATE and found no reaction. Finally, I called ICloud3_RESTART and then updated the location normally!
![image](https://user-images.githubusercontent.com/58241282/86200846-64db4d80-bb90-11ea-9563-c3d11cf1f8ce.png)

**Comment by a120578270** [comment] 2020-07-01 03:49
![image](https://user-images.githubusercontent.com/58241282/86201029-edf28480-bb90-11ea-984b-a07fcb7df0be.png)
It was found that more than one device did not get the location after invoking the restart service

**Comment by a120578270** [comment] 2020-07-01 03:51
2020-07-01 11:48:50 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] None (None) An error occurred sending a message to device iphone_lb. Error: The devicename can not be found. Message: {'message': 'request_location_update'}

**Comment by a120578270** [comment] 2020-07-01 03:58
2020-07-01 11:56:08 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] name 'trk_method_short_name' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2078, in _polling_loop_15_sec_icloud
    event_msg     = (f"{trk_method_short_name} update not completed, retrying")
NameError: name 'trk_method_short_name' is not defined
2020-07-01 11:56:08 ERROR (SyncWorker_2) [custom_components.icloud3.device_tracker] ►iCloud/FmF API Error, Error-<class 'ValueError'>

**Comment by gcobb321** [comment] 2020-07-02 00:17
I have fixed this in v2.2.0rc9 so am closing the issue regarding the error message. The error was created when formatting an error message about failing to connect to iCloud servers. The authentication time is empty indicating there was some type of connection failure Which is the root cause of the error message. Hopefully this is a rare event. The not_set and the iCloud3@00:00:00 point to this occurring while iCloud3 was starting up. 

I hope to put up v2.2.0rc9 in a couple of days. Right now I am chasing down a problem where 2 phones were in the same Stationary Zone, one leaves and then comes back. The iOS app issues a Region Entered for the other’s Stationary Zone which messes up a few things. It’s almost fixed but I need to do some more testing tomorrow. 

I’ll post a note here and close the issue when it’s available.

**Comment by a120578270** [comment] 2020-07-02 01:58
> 我已在v2.2.0rc9中修复此问题，因此正在关闭有关错误消息的问题。在格式化有关无法连接到iCloud服务器的错误消息的格式时，创建了该错误。身份验证时间为空，指示存在某种类型的连接失败，这是错误消息的根本原因。希望这是罕见的事件。not_set和iCloud3 @ 00：00：00指向在iCloud3启动时发生的情况。
> 
> 我希望在几天内发布v2.2.0rc9。现在，我要解决的问题是，有2部电话放在同一固定区中，有1部离开然后又回来。iOS应用会为对方的Stationary Zone发出一个“输入的区域”，这会弄乱一些事情。它几乎是固定的，但明天我需要做更多测试。
> 
> 我将在此处发布说明，并在有问题时予以解决。

2020-07-02 02:55:48 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=75845F46-BBCC-11EA-A8EF-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=75845F46-BBCC-11EA-A8EF-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2621, in _refresh_pyicloud_devices_location_data
    api_devices = self.api.devices
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 369, in devices
    service_root, self.session, self.params, self.with_family
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 424, in __init__
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 441, in refresh_client
    "deviceListVersion": 1,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 80, in request
    response = super(PyiCloudSession, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=75845F46-BBCC-11EA-A8EF-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again'))

Is this a network problem?

**Comment by a120578270** [comment] 2020-07-02 01:59
> I have fixed this in v2.2.0rc9 so am closing the issue regarding the error message. The error was created when formatting an error message about failing to connect to iCloud servers. The authentication time is empty indicating there was some type of connection failure Which is the root cause of the error message. Hopefully this is a rare event. The not_set and the iCloud3@00:00:00 point to this occurring while iCloud3 was starting up.
> 
> I hope to put up v2.2.0rc9 in a couple of days. Right now I am chasing down a problem where 2 phones were in the same Stationary Zone, one leaves and then comes back. The iOS app issues a Region Entered for the other’s Stationary Zone which messes up a few things. It’s almost fixed but I need to do some more testing tomorrow.
> 
> I’ll post a note here and close the issue when it’s available.

2020-07-02 02:55:48 ERROR (SyncWorker_7) [custom_components.icloud3.device_tracker] HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=75845F46-BBCC-11EA-A8EF-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=75845F46-BBCC-11EA-A8EF-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 2621, in _refresh_pyicloud_devices_location_data
    api_devices = self.api.devices
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 369, in devices
    service_root, self.session, self.params, self.with_family
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 424, in __init__
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 441, in refresh_client
    "deviceListVersion": 1,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 80, in request
    response = super(PyiCloudSession, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p26-fmipweb.icloud.com', port=443): Max retries exceeded with url: /fmipservice/client/web/refreshClient?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=75845F46-BBCC-11EA-A8EF-0011327B10D3&dsid=17169381464 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3428d6e10>: Failed to establish a new connection: [Errno -3] Try again'))

Is this a network problem?
Is this a network problem?

**Comment by a120578270** [comment] 2020-07-02 07:03
![image](https://user-images.githubusercontent.com/58241282/86326870-e5737a00-bc74-11ea-8d76-ea4c6c072d15.png)
Why is this version so easy for HA to error after rebooting, I have appeared many times to error in home! I see from the information panel when the error is generally the information is not fully acquired when!!

**Comment by a120578270** [comment] 2020-07-02 07:13
> ![image](https://user-images.githubusercontent.com/58241282/86326870-e5737a00-bc74-11ea-8d76-ea4c6c072d15.png)
> Why is this version so easy for HA to error after rebooting, I have appeared many times to error in home! I see from the information panel when the error is generally the information is not fully acquired when!!

I checked again. Is it always at home when the battery of the phone is dead or the status of the device is unavailable? If this is the case, It will cause me to mess with the automatic process!!

**Comment by gcobb321** [comment] 2020-07-02 08:12
Probably. The last set of error messages are the ones that indicate what is going on. The NeConnectionError with the max retries reached would imply it keeps trying for a connection but fail to get it. All this is happening in the pyicloud_ic3 program, which I did not right. (I took the pyicloud and modified it slightly’. 

It looks like your phone was authenticated at 2:56:14, the initial locate was done at 2:56:37 (trigger attribute) and last updated at 2:26:40. All during the initial locate after an HA restart.

If the battery is dead, HA would not be able to communicate with it. The dead battery statement will give me a place to look further. I’ll try putting mine into airplane mode, and turning it off and restarting HA to see if I can duplicate the problem here.

**Comment by a120578270** [comment] 2020-07-02 08:19
> Probably. The last set of error messages are the ones that indicate what is going on. The NeConnectionError with the max retries reached would imply it keeps trying for a connection but fail to get it. All this is happening in the pyicloud_ic3 program, which I did not right. (I took the pyicloud and modified it slightly’.
> 
> It looks like your phone was authenticated at 2:56:14, the initial locate was done at 2:56:37 (trigger attribute) and last updated at 2:26:40. All during the initial locate after an HA restart.
> 
> If the battery is dead, HA would not be able to communicate with it. The dead battery statement will give me a place to look further. I’ll try putting mine into airplane mode, and turning it off and restarting HA to see if I can duplicate the problem here.

I think whether it is the state of shutdown or when the location is not obtained, I hope that it will not be judged to be anywhere, which will lead to the automatic process judgment error, if not obtained, it can be judged to be the last location or the state in the acquisition, not home!

**Comment by a120578270** [comment] 2020-07-07 02:25
May I ask if icloud3 is not available now? Even if we tried the previous versions, the icloud data will not be obtained after starting HA, or the data will not be obtained after a period of time!

**Closed as completed** 2020-07-15 08:11 UTC
