### ISSUE TITLE
Zone Naming Issue Again

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#128] opened 2021-02-25 19:11 UTC
I'm having the hardest time getting my zone names to display correctly. I have 2 zones and it seems like I need to display each one differently to show up the way I want. 

My 2 zones are:
Art Class
Nani's House

I've set the display_zone_format to both fname and title and here's how each displays.

fname:
Art Class displays as ArtClass
Nani's House displays as Nani's House

title:
Art Class displays as Art Class
Nani's House displays as Nani S House

Why can't one of these options just take the name that I gave it in Home Assistant and stop messing with it?

**Comment by gcobb321** [comment] 2021-02-25 21:16
There is a bug dealing with the fname in v2.3.4. A fix is in the *development v2.3.5a * directory and I'm preparing the HACS update now. I introduced this problem when I let someone use the zone's friendly name on the *track_from_zone* parameter.

**Comment by gcobb321** [comment] 2021-02-25 22:04
#### v2.3.5 Bug Fix Update (2/25/2021) has just been released and is available on HACS and in the iCloud3 GitHub repository
- Fixed a bug causing the zone's friendly name to be displayed incorrectly that was introduced in v2.3.4. This only occurred when the zone's friendly name is more than one word,
- Added debug logging to the zone table load function
- Removed obsolete and unused 'IsOld' variables to prevent errors when location_data(IsOld) is not available.

**Comment by miraixyz** [comment] 2021-02-26 09:55
Still doesn't seem to solve the zone naming issue

**Comment by gcobb321** [comment] 2021-02-26 16:29
The zone names is stored in 2 places:
1. .storage\core.entity_registry
-- entity_id - the zone.entity_id made when the zone was added
-- unique_id - made when the zone was added
-- name - (fname) from the Configuration > Zone Name field when added
-- original_name - from the Configuration > Zone Name field when added

2. .storage\zone
-- name - from the Configuration > Zone > Name field
-- id - a unique value created when the zone was added that never changes

Normally, changing the name on the Config > Zone screen will change the name (fname) value in the entity_registry. However, it appears changing the name on the Config > Entity screen locks in the fname field and it will not be changed again if the name is changed on the Config > Zone screen.

The name (fname) field on the Config > Entity screen is the name used by the iOS App.

I would suggest deleting the Art Class Zone, readding it and restarting HA. I have just done this several times and it appears that the fname display works. Changing the name on the Config > Zone screen then changes the fname field and that works. Changing the fname on the Config > Entity > Name locks in the fname field and it will not change again on the Cofig > Zone.

The other option is just change the name on the Config > Entity > Name to 'Art Class' and restart iCloud3 (or HA).

**Comment by broyuken** [comment] 2021-02-26 17:01
The zone name is and always has been Art Class. I've never modified it, in fact I just created that zone a few days ago for the first time. For some reason ic3 changes it to Art_Class.

![image](https://user-images.githubusercontent.com/1593391/109331031-554cfb00-782a-11eb-8e39-fc0503529ce5.png)

**Comment by gcobb321** [comment] 2021-02-26 17:16
Go to Config > Developer Tools, scroll to bottom and look for zone.art_class. What is the *friendly_name* attribute? That is the value used by fname.

**Comment by broyuken** [comment] 2021-02-26 17:30
![image](https://user-images.githubusercontent.com/1593391/109334193-6566d980-782e-11eb-9536-881e3a5cf7a8.png)

**Comment by gcobb321** [comment] 2021-02-26 18:09
I just created 2 zones, Art Class & Barry's House. Then I moved my Home Zone and set the Art Class to my home location and set the *display_zone_format: fname* in the config_ic3.yaml file. Here are screen shots...
![Image1](https://user-images.githubusercontent.com/35449479/109337707-3d2da980-7833-11eb-9086-03da51718b79.jpg)

Everything looks fine on v2.3.5 unless I'm not understanding where the problem is being displayed
![2021-02-26_130837](https://user-images.githubusercontent.com/35449479/109338094-ce048500-7833-11eb-8002-9c998f343511.jpg)

**Comment by broyuken** [comment] 2021-02-26 18:13
I haven’t been able to test 2.3.5 yet, but this was an issue on .4. I’ll test again the next time I head to one of those zones, most likely Wednesday.

**Comment by gcobb321** [comment] 2021-02-26 18:16
Yes, it was an issue with v2.3.4 that was fixed in v2.3.5. And I'll be away all of next week.

**Comment by broyuken** [comment] 2021-02-26 18:42
No worries, I'll try to take note of it next time I'm out and leave you feedback for when you get back. It's not a breaking bug, just a visual thing.

**Comment by miraixyz** [comment] 2021-02-26 23:41
I was able to fix mine.  Here's what I did:
It seems that **display_zone_format: fname** _must_ be in the config_ic3.yaml.  Its not a matter of uncommenting it, because it does not exist by default (at least in mine it didn't).  I added this line and restarted icloud3 and the spaces in the display name were back.

BTW, I don't use the config_ic3.yaml file, and adding just that one line was fine.

**Closed as completed** 2021-03-04 23:22 UTC
