### ISSUE TITLE
max_interval settings not described in the docs

### ISSUE THREAD

**Issue by xvolte** [gcobb321/icloud3#68] opened 2020-08-25 14:10 UTC
Hello again,

can't find the description of "max_interval"in the github doc.

https://gcobb321.github.io/icloud3/#/chapters/2-config-parms

Thanks in advance,

**Comment by gcobb321** [comment] 2020-08-25 18:13
It was replaced by the inzone_interval parameter and should not have been included in the sample files. Would you find it useful? It would typically apply when you are a long distance from Home and the calculated Interval time is very large and probably wouldn't be a big deal to add.

**Comment by xvolte** [comment] 2020-08-25 18:52
i don't know i have trouble understanding the doc.

there is the inzone_interval and the dynamic_zone_interval : but i don't really understand what is the difference.
looks like the inzone is always referring to the home ? whereas dynamic zone is location where you do not move for a certain period of time (correct?)

Question is : When you are moving (driving, or cycling) what settings should i use to ask for location updates (like every 5 minutes for example)

**Comment by a120578270** [comment] 2020-08-26 09:39
> 它已由inzone_interval参数代替，不应包含在示例文件中。您会觉得有用吗？通常，当您离家很远且计算出的间隔时间非常大时，可能不需要多花钱。

I also have a question if you have multiple places like Home, company 1, company 2. If the current state is not home, will the inzone_interval time be calculated based on the nearest location or just the distance to home? Previous versions of RC10 had a maximum inzone_interval of only 1HRS, and rc11E had a maximum of 4Hrs.

![image](https://user-images.githubusercontent.com/58241282/91287987-0531a500-e7c3-11ea-82b2-26bea3fd1262.png)

**Comment by a120578270** [comment] 2020-08-26 09:40
> It was replaced by the inzone_interval parameter and should not have been included in the sample files. Would you find it useful? It would typically apply when you are a long distance from Home and the calculated Interval time is very large and probably wouldn't be a big deal to add.

I also have a question if you have multiple places like Home, company 1, company 2. If the current state is not home, will the inzone_interval time be calculated based on the nearest location or just the distance to home? Previous versions of RC10 had a maximum inzone_interval of only 1HRS, and rc11E had a maximum of 4Hrs.

![image](https://user-images.githubusercontent.com/58241282/91288185-42963280-e7c3-11ea-8b9e-ab87a153641b.png)

**Comment by gcobb321** [comment] 2020-08-26 14:53
Fixed in 11f

* Fixed a bug introduced in rc11e resulting in a 4 hrs Interval when not in a zone. This was caused by testing if the max_interval > interval when it should been interval > max_interval. If the max_interval is used, the Interval that is displayed will be max_interval(interval), e.g., '4 hrs(7.5 hrs)'.

Side note:
There are 3 parameters dealing with the interval between polling:
* inzone_interval - the interval when in a zone (any zone)
* stationary_zone_interval - interval when in a stationary zone (formally a dynamic stationary zone because the location changes)
* max_interval - when the interval calculated using the Waze travel time exceeds the max_interval, the max_interval is used

and:
* 1 hr - if the calculated distance is greater than the waze_max_distance, the interval is set to 1 hr

**Closed as completed** 2020-09-27 14:36 UTC
