### ISSUE TITLE
2.2.1a zone formatting

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#94] opened 2020-11-06 16:38 UTC
I'm not sure what changes were made between 2.2 and 2.2.1a but the formatting for my zones is now all messed up. 
I have a zone for my in laws house where the zone name is  nani_s_house. In 2.2 the name was displayed correctly as Nani's House, and the device tracker built into the iOS app still displays it correctly. However the iCloud3 zone name now displays as NaniSHouse. 

Between this issue and https://github.com/gcobb321/icloud3/issues/90#event-3967881073 it seems like you made some significant changes to how zone names are formatted and displayed. I would recommend these be changed back as they are causing some issues, whereas they were working perfectly before. 

Going back to 2.2 again until this is resolved or there is a manual fix available I can test with.

**Comment by gcobb321** [comment] 2020-11-06 16:49
The differences between the iOS App using the friendly name and iCloud3 using the zone's actual name were causing a lot of problems and unnecessary zone changes. The *display_zone_fname: True* should put the friendly name in the *device_tracker.{DEVICENAME}* state and match what you were using. There are several zone formats that used to be *sensor.zone_name1, _name2, & _name3*. They are still available but you should also see *sensor.zone_fname, sensor_zone_title, & sensor.zone_name* entities. One should be the format you want. Look at the *Developer Tools > State* screen to see them.

The iCloud3 User Manual has some examples of the formatting [here](https://gcobb321.github.io/icloud3/#/chapters/2-sensors?id=zone-sensors).

Let me know if one works or nothing works.

**Comment by broyuken** [comment] 2020-11-08 18:54
I’m not sure where to put that field. Also, could we use the zone title instead of the fname? That is the formatting I was using in 2.2.

**Comment by gcobb321** [comment] 2020-11-08 20:23
To make sure I understand. Of the 3 zone formats that are available, you would like to see the *zone title* In the *Zone* field, not the *Zone Fname*. That could be done by changing the parameter *display_zone_fname: True/Falsa* to *display_zone_format: Name/Fname/Title/Zone*. That shouldn't be difficult and I'll look into it.

**Comment by broyuken** [comment] 2020-11-08 21:56
I would like to see it on lovelace when I have my device tracker entity in a card.

**Comment by gcobb321** [comment] 2020-11-09 20:50
iCloud3 v2.2.2d has been uploaded to the development-v2.2.2 directory [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.2.2)
____________________________________________________________
iCloud3 now works with Real 2fa Support
------------------
This is significant update to iCloud3. It supports true 2fa verification using the 6-digit Apple ID Verification Code sent from Apple when you log into iCloud.

Download the zip file from the development-v2.2.2 directory [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.2.2), unzip it into the icloud3 directory and restart HA.

When iCloud3 starts, you will get the standard Apple Login warning and the 6-digit Apple ID Verification Code notification. YOU WILL USE THAT 6-DIGIT CODE IN THE ID ENTRY SCREEN ON THE HA NOTIFICATIONS AREA. Select the Verification Code entry window like you always have from the HA Notifications area and enter the 6-digit code. This will create the Trusted Device token like other apps and browsers. iCloud3 will then continue starting as it usually does.

Other changes:
---------------------
Deleted parameter
*display_zone_fname: True/False* has been eliminated.

New Parameter:
*display_zone_format: name/title/fname/zone,  Default: name*

This parameter indicates how the zone should be displayed in the device_tracker.[DEVICENAME] states field and on the Event Log. The zone is formatted as follows:
- name - A reformatted zone name. Examples: 'the_shores' is displayed as 'TheShores' 
- title - A reformatted zone name. Example: 'the_shores' is displayed as 'The Shores'
- fname - The zones Friendly Name. Example: 'The Shores Development'
- zone - The actual zone name is displayed. Example: 'the_shores' is displayed as 'the_shores'


Bug Fix (I think)
-----------------
The *sensor.[DEVICENAME_last_zone* values should be correct.

**Comment by gcobb321** [comment] 2020-11-09 20:56
I haven't announced this yet on the v2.2 Forum yet. I thought I'd release it to you first. Let me know if everything works OK or doesn't work. Also, look at the last_zone values and  let me know if they are correct.

**Comment by broyuken** [comment] 2020-11-10 16:18
Where do I put this display_zone_format parameter?

Like this?
```
platform: icloud3
username: !secret icloud3_username
password: !secret icloud3_password
display_zone_format: title
track_devices:
  - my_iphone > 11111111@gmail.com
  - wifes_iphone > 22222222@gmail.com
```

**Comment by broyuken** [comment] 2020-11-10 16:56
I have uploaded the newest version, and have changed to family sharing. I now have all my devices listed which closes https://github.com/gcobb321/icloud3/issues/92 after making that configuration change. I cannot test the zone name right now as I am home, and don't plan on going anywhere today but I will keep an eye on it next time I venture out.

**Comment by gcobb321** [comment] 2020-12-13 20:56
This should be fixed now. Reopen the issue is you find a problem. Release Candidate 7 was just uploaded.

**Closed as completed by gcobb321** 2020-12-13 20:56 UTC

**Comment by broyuken** [comment] 2020-12-14 11:23
Sorry yes this was fixed with your last update.
